version: "3.3"
services:
   tgbot:
    build:
      context: ./apps
      dockerfile: Dockerfile-tgbot
    env_file:
      - tgbot.env
    depends_on:
      - db


   db:
     image: mariadb
     restart: always
     env_file:
       - tgbot.env
